from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import Response
import os
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.util import get_remote_address
from slowapi.errors import RateLimitExceeded
from routes_auth import router as auth_router
from routes_sabores import router as sabores_router
from routes_eventos import router as eventos_router
from routes_pedidos import router as pedidos_router
from routes_dashboard import router as dashboard_router
from routes_pagamentos import router as pagamentos_router
from routes_pizza_config import router as pizza_config_router
from routes_votacoes import router as votacoes_router
from routes_feedbacks import router as feedbacks_router
from routes_admin import router as admin_router
from database import get_db_connection


def run_migrations():
    """Executa migrações automáticas no startup (idempotente)"""
    migrations = [
        # Adicionar coluna pagamento_liberado à tabela eventos
        "ALTER TABLE eventos ADD (pagamento_liberado NUMBER(1) DEFAULT 0)",
        # Tabela de Auditoria (Fase 3)
        """
        CREATE TABLE auditoria_logs (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            usuario_id NUMBER,
            acao VARCHAR2(100),
            detalhes VARCHAR2(300),
            ip_address VARCHAR2(50),
            data_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    ]
    
    try:
        with get_db_connection() as conn:
            cursor = conn.cursor()
            for sql in migrations:
                try:
                    cursor.execute(sql)
                    conn.commit()
                    print(f"[MIGRATION] OK: {sql[:60]}...")
                except Exception as e:
                    # ORA-01430: column already exists — ignorar
                    if "01430" in str(e) or "already exists" in str(e).lower():
                        pass
                    else:
                        print(f"[MIGRATION] Erro (ignorado): {e}")
            cursor.close()
    except Exception as e:
        print(f"[MIGRATION] Erro de conexão (ignorado): {e}")


# Executar migrações no startup
run_migrations()

# Rate limiter global
limiter = Limiter(key_func=get_remote_address)

IS_PRODUCTION = os.getenv("VERCEL", "") == "1" or os.getenv("PRODUCTION", "") == "1"

app = FastAPI(
    title="PIZZADA DO LELO API",
    description="API para gerenciamento de pedidos de pizza nos eventos mensais",
    version="1.0.0",
    docs_url=None if IS_PRODUCTION else "/docs",
    redoc_url=None if IS_PRODUCTION else "/redoc",
    openapi_url=None if IS_PRODUCTION else "/openapi.json",
)

app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

# Configurar CORS — apenas origens permitidas
allowed_origins = [
    "https://pizzada.vercel.app",
    "http://localhost:5173",
    "http://localhost:3000",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=allowed_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Security headers middleware
@app.middleware("http")
async def add_security_headers(request: Request, call_next):
    response: Response = await call_next(request)
    response.headers["X-Content-Type-Options"] = "nosniff"
    response.headers["X-Frame-Options"] = "DENY"
    response.headers["X-XSS-Protection"] = "1; mode=block"
    response.headers["Referrer-Policy"] = "strict-origin-when-cross-origin"
    return response

# Registrar rotas
app.include_router(auth_router)
app.include_router(sabores_router)
app.include_router(eventos_router)
app.include_router(pedidos_router)
app.include_router(dashboard_router)
app.include_router(pagamentos_router)
app.include_router(pizza_config_router)
app.include_router(votacoes_router)
app.include_router(feedbacks_router)
app.include_router(admin_router)

# Servir arquivos estáticos
app.mount("/static", StaticFiles(directory="static"), name="static")

@app.get("/")
async def root():
    return {
        "message": "Bem-vindo à PIZZADA DO LELO! 🍕",
        "version": "1.0.0",
        "docs": "/docs"
    }

@app.get("/health")
async def health_check():
    """Endpoint para verificar saúde da API"""
    return {"status": "ok", "message": "API está funcionando!"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)