-- Migration: Criar tabela pizza_configs para salvar configurações de montagem de pizzas
-- Esta tabela armazena os overrides de pareamento e setor definidos pelo admin

-- Criar tabela
CREATE TABLE pizza_configs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id NUMBER NOT NULL,
    pairing_overrides CLOB DEFAULT '{}',
    sector_overrides CLOB DEFAULT '{}',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pizza_config_evento FOREIGN KEY (evento_id) REFERENCES eventos(id) ON DELETE CASCADE,
    CONSTRAINT uq_pizza_config_evento UNIQUE (evento_id)
);

-- Criar índice
CREATE INDEX idx_pizza_configs_evento ON pizza_configs(evento_id);

-- Trigger para atualizar updated_at
CREATE OR REPLACE TRIGGER trg_pizza_configs_update
BEFORE UPDATE ON pizza_configs
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/
