-- PIZZADA DO LELO - Supabase/PostgreSQL schema
-- Fonte de verdade: schema Oracle usado pelo backend atual.

create table usuarios (
    id integer generated by default as identity primary key,
    nome_completo varchar(200) not null,
    senha_hash varchar(255) not null,
    setor varchar(100) not null,
    is_admin boolean default false,
    ativo boolean default true,
    data_cadastro timestamptz default now(),
    email varchar(255) not null unique,
    constraint uk_usuario_nome unique (nome_completo)
);

create table sabores_pizza (
    id integer generated by default as identity primary key,
    nome varchar(100) not null,
    preco_pedaco numeric(10, 2) not null,
    ativo boolean default true,
    data_cadastro timestamptz default now(),
    descricao text,
    tipo varchar(20) default 'SALGADA',
    constraint uk_sabor_nome unique (nome),
    constraint sabores_pizza_tipo_check check (tipo in ('SALGADA', 'DOCE'))
);

create table eventos (
    id integer generated by default as identity primary key,
    data_evento date not null,
    status varchar(20) default 'ABERTO',
    data_limite timestamptz not null,
    data_criacao timestamptz default now(),
    nome varchar(255),
    tipo varchar(20) default 'NORMAL',
    pagamento_liberado boolean default false,
    constraint uk_evento_data unique (data_evento),
    constraint eventos_status_check check (status in ('ABERTO', 'FECHADO', 'FINALIZADO')),
    constraint eventos_tipo_check check (tipo in ('NORMAL', 'RELAMPAGO'))
);

create table evento_acessos (
    evento_id integer not null references eventos(id) on delete cascade,
    usuario_id integer not null references usuarios(id) on delete cascade,
    primary key (evento_id, usuario_id)
);

create table pedidos (
    id integer generated by default as identity primary key,
    evento_id integer not null references eventos(id),
    usuario_id integer not null references usuarios(id),
    valor_total numeric(10, 2) not null,
    valor_frete numeric(10, 2) default 1.00,
    status varchar(20) default 'PENDENTE',
    data_pedido timestamptz default now(),
    constraint pedidos_status_check check (status in ('PENDENTE', 'CONFIRMADO', 'PAGO'))
);

create table itens_pedido (
    id integer generated by default as identity primary key,
    pedido_id integer not null references pedidos(id) on delete cascade,
    sabor_id integer not null references sabores_pizza(id),
    quantidade integer not null,
    preco_unitario numeric(10, 2) not null,
    subtotal numeric(10, 2) not null
);

create table pizza_configs (
    id integer generated by default as identity primary key,
    evento_id integer not null unique references eventos(id) on delete cascade,
    pairing_overrides jsonb default '{}'::jsonb,
    sector_overrides jsonb default '{}'::jsonb,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    number_overrides jsonb default '{}'::jsonb
);

create table codigos_reset_senha (
    id integer generated by default as identity primary key,
    usuario_id integer not null references usuarios(id) on delete cascade,
    codigo varchar(10) not null,
    data_expiracao timestamptz not null,
    usado boolean default false,
    data_criacao timestamptz default now()
);

create table votacoes (
    id integer generated by default as identity primary key,
    titulo varchar(200) not null,
    data_abertura timestamptz not null,
    data_limite timestamptz not null,
    data_resultado_ate timestamptz not null,
    status varchar(20) default 'ABERTO',
    criado_por integer not null references usuarios(id),
    data_criacao timestamptz default now(),
    constraint votacoes_status_check check (status in ('ABERTO', 'FECHADO', 'FINALIZADO'))
);

create table votacao_escolhas (
    id integer generated by default as identity primary key,
    votacao_id integer not null references votacoes(id) on delete cascade,
    texto varchar(200) not null,
    ordem integer not null,
    constraint uk_escolha_ordem unique (votacao_id, ordem)
);

create table votos (
    id integer generated by default as identity primary key,
    escolha_id integer not null references votacao_escolhas(id) on delete cascade,
    usuario_id integer not null references usuarios(id),
    data_voto timestamptz default now(),
    constraint uk_voto_unico unique (escolha_id, usuario_id)
);

create table feedbacks (
    id integer generated by default as identity primary key,
    usuario_id integer references usuarios(id),
    categoria varchar(30) not null,
    mensagem text not null,
    anonimo boolean default false,
    data_criacao timestamptz default now(),
    constraint feedbacks_categoria_check check (categoria in ('ELOGIO', 'SUGESTAO', 'PROBLEMA', 'OUTRO'))
);

create table auditoria_logs (
    id integer generated by default as identity primary key,
    usuario_id integer,
    acao varchar(100),
    detalhes varchar(300),
    ip_address varchar(50),
    data_hora timestamptz default now()
);

create index idx_pedido_evento on pedidos(evento_id);
create index idx_pedido_usuario on pedidos(usuario_id);
create index idx_item_pedido on itens_pedido(pedido_id);
create index idx_item_sabor on itens_pedido(sabor_id);
create index idx_evento_status on eventos(status);
create index idx_acesso_evento on evento_acessos(evento_id);
create index idx_acesso_usuario on evento_acessos(usuario_id);
create index idx_pizza_configs_evento on pizza_configs(evento_id);
create index idx_reset_usuario on codigos_reset_senha(usuario_id);
create index idx_votacao_status on votacoes(status);
create index idx_votacao_datas on votacoes(data_abertura, data_limite, data_resultado_ate);
create index idx_escolha_votacao on votacao_escolhas(votacao_id);
create index idx_voto_escolha on votos(escolha_id);
create index idx_voto_usuario on votos(usuario_id);
create index idx_feedback_data on feedbacks(data_criacao desc);
create index idx_auditoria_usuario on auditoria_logs(usuario_id);
create index idx_auditoria_data on auditoria_logs(data_hora desc);

create or replace function update_pizza_configs_timestamp()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

create trigger trg_pizza_configs_update
before update on pizza_configs
for each row
execute function update_pizza_configs_timestamp();

create or replace function check_voto_unico()
returns trigger as $$
declare
    v_votacao_id integer;
    v_count integer;
begin
    select votacao_id into v_votacao_id
    from votacao_escolhas
    where id = new.escolha_id;

    select count(*) into v_count
    from votos v
    join votacao_escolhas e on v.escolha_id = e.id
    where e.votacao_id = v_votacao_id
      and v.usuario_id = new.usuario_id;

    if v_count > 0 then
        raise exception 'Usuario ja votou nesta votacao';
    end if;

    return new;
end;
$$ language plpgsql;

create trigger trg_voto_unico_votacao
before insert on votos
for each row
execute function check_voto_unico();
